Repository BluEye-Robotics/blueye.sdk, pull requests merged in 2019-12, with the labels that each got.

#61 Add tip to use iPython to explore documentation
  docs/quick_start.md
Labels: documentation

#60 Store drone info on connection
  blueye/sdk/diagnostics.py
  blueye/sdk/pioneer.py
  tests/test_sdk.py
Labels: enhancement

#63 Expose battery state of charge and camera record time
  blueye/sdk/camera.py
  blueye/sdk/pioneer.py
  tests/test_sdk.py
Labels: documentation, enhancement
