Repository BluEye-Robotics/blueye.sdk, pull requests merged in 2019-11, with the labels that each got.

#39 Add support for browsing logfiles
  .gitattributes
  blueye/sdk/logs.py
  blueye/sdk/pioneer.py
  docs/logs/listing-and-downloading.md
  docs/logs/log-file-format.md
  docs/logs/plotting.md
  docs/media/depth_plot.svg
  poetry.lock
  pyproject.toml
  tests/test_logs.py
Labels: enhancement

#44 Test on python 3.8
  .github/workflows/Tests.yml
  docs/quick_start.md
  poetry.lock
  pyproject.toml
Labels: enhancement

#46 Add webdav instructions
  docs/video/downloading-videos.md
  docs/video/downloading.md
  poetry.lock
  pyproject.toml
Labels: documentation

#51 Publish documentation to PyPI
  .github/workflows/PublishRelease.yml
  .gitignore
  blueye/sdk/__init__.py
  blueye/sdk/utils.py
  docs/quick_start.md
  pyproject.toml
  tests/test_sdk.py
Labels: documentation, enhancement

#50 Add missing dependencies
  poetry.lock
  pyproject.toml
Labels: bug

#58 Document when log files are started and stopped
  docs/logs/listing-and-downloading.md
Labels: documentation

#57 Document file name formats for WebDAV
  docs/video/downloading.md
Labels: documentation
